newsfeed/urls.py
from django.urls import path

from . import views

app_name = 'newsletter'
urlpatterns = [
    path('', views.newsletter_signup, name='newsletter_signup'),
    path('unsubscribe/', views.newsletter_unsubscribe, name='newsletter_unsubscribe')
]

newsletter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsfeed.urls', namespace='newsletter'))
]

newsfeed/models.py
from django.db import models

class NewsletterUser(models.Model):
    email = models.EmailField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

class Newsletter(models.Model):
    EMAIL_STATUS_CHOICE = (
        ('Draft', 'Draft'),
        ('Published', 'Published')
    )
    subject = models.CharField(max_length=255)
    body = models.TextField()
    email = models.ManyToManyField(NewsletterUser)
    status = models.CharField(max_length=10, choices=EMAIL_STATUS_CHOICE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

newsfeed/forms.py
from django import forms

from .models import NewsletterUser

class NewsletterUserSignupForm(forms.ModelForm):
    class Meta:
        model = NewsletterUser
        fields = ['email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        return email

newsfeed/views.py
from django.shortcuts import render
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import get_template

from .models import NewsletterUser, Newsletter
from .forms import NewsletterUserSignupForm

def newsletter_signup(request):
    form = NewsletterUserSignupForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        if NewsletterUser.objects.filter(email=instance.email).exists():
            messages.warning(request, 'Your Email already exists in our databasee',
                             'alert alert-warning alert-dismissible'
                             )
        else:
            instance.save()
            messages.success(request, 'Your Email has been submitted successfuly',
                             'alert alert-success alert-dismissible'
                             )
            subject = 'Thank you for subscribing to our newsletter'
            from_email = settings.EMAIL_HOST_USER
            to_email = [instance.email]
            with open(settings.BASE_DIR / 'templates/newsfeed/sign_up_email.txt') as f:
                signup_message = f.read()
            message = EmailMultiAlternatives(
                subject=subject,
                body=signup_message,
                from_email=from_email,
                to=to_email
            )
            html_template = get_template('newsfeed/sign_up_email.html').render()
            message.attach_alternative(html_template, 'text/html')
            message.send()

    context = {
        'form': form,

    }
    return render(request, 'newsfeed/index.html', context)

def newsletter_unsubscribe(request):
    form = NewsletterUserSignupForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        if NewsletterUser.objects.filter(email=instance.email).exists():
            NewsletterUser.objects.filter(email=instance.email).delete()
            messages.success(request, 'Your Email has been removed from our database',
                             'alert alert-success alert-dismissible'
                             )
            subject = 'You have successfuly unsubscribed from our Newsletter'
            from_email = settings.EMAIL_HOST_USER
            to_email = [instance.email]

            with open(settings.BASE_DIR / 'templates/newsfeed/unsubscribe_email.txt') as f:
                signup_message = f.read()
            message = EmailMultiAlternatives(
                subject=subject,
                body=signup_message,
                from_email=from_email,
                to=to_email
            )
            html_template = get_template('newsfeed/unsubscribe_email.html').render()
            message.attach_alternative(html_template, 'text/html')
            message.send()

        else:
            messages.warning(request, 'Your email does not exist in our database',
                             'alert alert-warning alert-dismissible'
                             )

    context = {
        'form': form,

    }
    return render(request, 'newsfeed/unsubscribe.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <title>Newsletter</title>

</head>
<body>
{% block content %}
    <!--content goes here-->
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/newsfeed/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="newsletter8 py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <h6 class="text-themecolor font-weight-normal text-uppercase">newsletter</h6>
                    <h4 class="my-3">Stay informed about new and upcoming causes</h4>
                    <h6 class="subtitle mt-3 font-weight-normal">It has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</h6>
                    {% if messages %}
                        {% for message in messages %}
                            <div {% if message.tags %}  class="{{ message.tags}}" {% endif %} role="alert">
                                {{message}}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% else %}
                        <form method="POST" action="#" class="mt-4">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form }}
                            </div>
                            <div class="form-group">
                                <button class="btn btn-danger-gradiant btn-block btn-md text-uppercase text-white border-0" type="submit">Subscribe </button>
                            </div>
                            <div class="form-group">
                                <div class="my-1">
                                    <div class="custom-control custom-checkbox mr-sm-2">
                                        <input id="customControlAutosizing1" class="custom-control-input" type="checkbox" />
                                        <label class="custom-control-label" for="customControlAutosizing1">I have read and agree to the <a class="text-decoration-none" href="#">terms and conditions</a></label></div>
                                </div>
                            </div>
                        </form>
                    {% endif %}
                </div>
                <div class="col-lg-6 ml-auto">
                    <div class="d-block d-md-flex border-bottom pb-3 text-uppercase">
                        <h6 class="no-shrink font-weight-medium align-self-center m-b-0">Latest News</h6><a class="ml-auto text-danger align-self-center text-decoration-none" href="#">View All</a>
                    </div>
                    <div class="row blog-row mt-4 mb-3">
                        <div class="col-md-4"><a href="#"><img class="img-fluid" src="https://www.wrappixel.com/demos/ui-kit/wrapkit/assets/images/blog/blog-home/img12.jpg" alt="wrapkit" /></a></div>
                        <div class="col-md-8">
                            <h5><a class="text-decoration-none" href="#">The Universe is all of time and space and its contents.</a></h5>
                            <p>by <a class="text-decoration-none" href="#">Mark Freeman</a> / 23 May 2017</p>
                        </div>
                    </div>
                    <div class="row blog-row my-3">
                        <div class="col-md-4"><a href="#"><img class="img-fluid" src="https://www.wrappixel.com/demos/ui-kit/wrapkit/assets/images/blog/blog-home/img13.jpg" alt="wrapkit" /></a></div>
                        <div class="col-md-8">
                            <h5><a class="text-decoration-none" href="#">Pellentesque mollis eros quis massa interdum porta et vel.</a></h5>
                            <p>by <a class="text-decoration-none" href="#">Mark Freeman</a> / 23 May 2017</p>
                        </div>
                    </div>
                    <div class="row blog-row my-3">
                        <div class="col-md-4"><a href="#"><img class="img-fluid" src="https://www.wrappixel.com/demos/ui-kit/wrapkit/assets/images/blog/blog-home/img14.jpg" alt="wrapkit" /></a></div>
                        <div class="col-md-8">
                            <h5><a class="text-decoration-none" href="#">Duis vel viverra quamam molesvulputate femy.</a></h5>
                            <p>by <a class="text-decoration-none" href="#">Mark Freeman</a> / 23 May 2017</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/newsfeed/sign_up_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Welcome to snipherDev Online</h2>
<p>Thank you for joining</p>
<p>To unsubscribe please visit this link visit
    <a href="#">Unsubscribe</a>
</p>
</body>
</html>

templates/newsfeed/unsubscribe.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <main>

        <div class="main">

            <div class="container">

                <div class="aside">
                    <div class="newsletter">

                        <h2 class="h2">Newsletter</h2>

                        <div class="wrapper">

                            <p>
                                Unsubscribe from our newsletter, this action will stop you from getting our latest updates.
                            </p>

                            {% if messages %}
                                {% for message in messages %}
                                    <div {% if message.tags %}  class="{{ message.tags}}" {% endif %} role="alert">
                                        {{message}}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <form method="POST" action="#">
                                    {% csrf_token %}
                                    {{ form }}
                                    <button type="submit" class="btn btn-primary">Unsubscribe</button>
                                </form>
                            {% endif %}

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </main>


{% endblock %}

templates/newsfeed/unsubscribe_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Sorry to see you Leave</h2>
<p>bye bye</p>
<p>To subscribe again please visit this link visit
    <a href="{% url 'newsletter:newsletter_signup' %}">subscribe</a>
</p>
</body>
</html>